### ISSUE TITLE
Install Indruductions

### ISSUE THREAD

**Issue by ddinternetagentur** [sillyfrog/OctoPrint-Klipper-mjpg-Dockerfile#1]
Hi Sillyfrog,

can you make a manual for stupid? Somehow this does not work for me .. I am very disappointed with docker because I want to print and nothing works: D I always use your files but in the end it does not work properly. Could you build a short step by step instruction there? Would be very nice

**Comment by sillyfrog** [comment]
The README should outline everything you need to do. Have you flashed the firmware on your printer yet? Also be sure that the path to your serial port is correct (ignore anything to do with video for the moment).
I'm assuming you can build this image using the Dockerfile OK?

**Comment by ddinternetagentur** [comment]
Hi, my Printer has the klipper Firmware yes.

I download you files, put it on my docker and start with my User: donikdesign this:
~~~
docker build . --file Dockerfile.KlipperOctoprint -t ko
~~~

but here come this errors

~~~

###### Launching Klipper host software...
Restarting klipper: klipperStopping klipper: klipper.
Starting klipper: klipperstart-stop-daemon: user '--user' not found
 failed!

~~~

**Comment by ddinternetagentur** [comment]
And when i try:

~~~
docker run -d -v /etc/localtime:/etc/localtime:ro -v /octoprint:/home/octoprint/.octoprint \
    --device /dev/ttyUSB0:/dev/ttyUSB0 \
    -p 5000:5000 \
    ko
~~~

this error:

~~~
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/klippyoctostart.py\": permission denied": unknown.
~~~

**Comment by sillyfrog** [comment]
That error `Launching Klipper host software` can be ignored.

What OS are you running Docker on? Given the command to start Docker, it looks like Linux (which is what you need). That last error is what happens when the execute bit is not set, I'm not sure what could be stuffing that up. There probably a way to set the execute bit on Windows, not sure how. On Linux/Mac, if you run `chmod +x *.py`, then rebuild, that should get you past that error at least. Also, check if `selinux` is enabled, as that could also be causing fun (and disable it and reboot and try again).

Also, can I get you to also try the default `Dockerfile` (shouldn't make a difference, but who knows).

**Comment by sillyfrog** [comment]
No response after several months, assume resolved.
